Output .github/assets/demo.webm

Require dotkeep
Require echo

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 20
Set BorderRadius 20
Set Width 1260
Set Height 840
Set Margin 0
#Set MarginFill "#111122"
Set Padding 20
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 40

Type@200ms "dotkeep"
Sleep 100ms
Enter
Sleep 3s
# header
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# commands
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# init
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# config
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# sample
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# Where
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# Backup
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
# Restore
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 5ms
Type j Sleep 3s
