Output .github/assets/help.webm

Require dotkeep
Require echo

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 24
Set BorderRadius 20
Set Width 1260
Set Height 1300
Set Margin 80
Set MarginFill "#111122"
Set Padding 30
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 80

Type "dotkeep"
Sleep 1s
Enter
Hide
ScrollUp 100
Show
Sleep 3s
ScrollDown@60ms 5 # init
Sleep 3s
ScrollDown@60ms 7 # config
Sleep 3s
ScrollDown@60ms 31 # where
Sleep 3s
ScrollDown@60ms 11 # backup
Sleep 3s
ScrollDown@60ms 18 # restore
Sleep 3s
ScrollDown@60ms 30 # tail
Sleep 3s
