Output .github/assets/help.webm

Require dotkeep
Require echo

Set TypingSpeed 80ms

Set Shell "bash"
Set FontSize 24
Set BorderRadius 20
Set Width 1086
Set Height 1140
Set Margin 0
#Set MarginFill "#111122"
Set Padding 20
Set Theme "Dark Pastel"
Set WindowBar Colorful
Set WindowBarSize 40

Type "dotkeep"
Sleep 1s
Enter
Hide
ScrollUp 100
Show
Sleep 1s
ScrollDown@30ms 6 # init
Sleep 1s
ScrollDown@30ms 9 # config
Sleep 1s
ScrollDown@30ms 34 # where
Sleep 1s
ScrollDown@30ms 11 # backup
Sleep 1s
ScrollDown@30ms 14 # restore
Sleep 1s
ScrollDown@30ms 30 # tail
Sleep 1s
